[package]
name = "regex-bench"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
regex = "1.5.4"
regex-syntax = "0.6.25"

[[bench]]
name = "bench"
harness = false
